-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- map("n", "<leader>rn", rest_nvim.run({ desc = "Execute nvim.tree in file" }))
